<?php

namespace AppBundle\Repository;

/**
 * VideoGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
